
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhkqjbepwbuwwbeyvfvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoa3FqYmVwd2J1d3diZXl2ZnZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTIzMDMsImV4cCI6MjA1ODY2ODMwM30.kReFoEkEKDD4de1epbpelHT4iYIgTFObfN2hfJvAXw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    },
    db: {
      schema: 'public',
    }
  }
);

// Function to handle anonymous authentication
export const ensureAnonymousUser = async () => {
  const { data: { session } } = await supabase.auth.getSession();
  
  if (!session) {
    // Create anonymous session if none exists
    await supabase.auth.signInAnonymously();
  }
  
  return supabase.auth.getSession();
};
